FROM python:3.9-slim

# Establecemos directorio de trabajo
WORKDIR /usr/src/app

# Instalación de dependencias
COPY ./requirements.txt /usr/src/app/requirements.txt
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Copia del proyecto
COPY ./src /usr/src/app/src

# Exponemos puerto para Streamlit
EXPOSE 8501

# Comando para iniciar Streamlit
CMD ["streamlit", "run", "src/dashboard.py", "--server.port=8501", "--server.address=0.0.0.0"]
